### ISSUE TITLE
Still cannot download the data sets

### ISSUE THREAD

**Issue by ericvivian** [SilvioGiancola/TrackingNet-devkit#19] opened 2020-04-08 21:12 UTC
Was able to download the *zip files from the backup Google links, though the links provide only image data, not annotation. 

How to download the annotation files? 

The dev-kit method does not work - with permission-denied messages. 

Thanks.

**Comment by SilvioGiancola** [comment] 2020-04-09 15:14
Dear @ericvivian, are you referring those those backup [links](https://github.com/SilvioGiancola/TrackingNet-devkit/issues/2#issuecomment-590915323)?
Which split in particular? Are you sure you have downloaded it completely? They should weight around 90GB each, 34GB for training.

As far as I am concerned, those backup links contains 2 folders: 
 - zips: with all the sequences (.zip)
 - anno: with all the annotation files (.txt)

**Comment by HubHop** [comment] 2020-04-19 01:54
Hi @SilvioGiancola, thanks for your excellent work.

I cannot download the datasets via those backup links, it seems that google limits download and the download is very unstable. I've tried so many times but the download terminated frequently. Do you have any plan on uploading the dataset onto other platforms, like Baidu or Dropbox?

Many thanks.

**Comment by SilvioGiancola** [comment] 2020-04-21 17:06
Hi @HubHop, 

Unfortunately any storage service like Baidu, Dropbox or AWS enforces a limitation on the bandwidth.

As an experimental solution, I am currently rolling out a torrenting option from [academictorrents.com](https://academictorrents.com/details/1faf1b53cc0099d2206f02be42b5688952c3c6b3). It may very slow at the beginning, but I expect it will improve as many people are asking for a copy of TrackingNet. I hope everyone will play fair and **seed there torrent** as I am currently doing.

**Comment by SilvioGiancola** [comment] 2020-04-22 03:37
Duplicate of #2

**Closed by SilvioGiancola** 2020-04-22 03:37 UTC
